// tickers
export const LOAD_TICKERS = 'LOAD_TICKERS';

// prices
export const LOAD_PRICES = 'LOAD_PRICES';

// portfolio
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const LOAD_PORTFOLIO_ASSETS = 'LOAD_PORTFOLIO_ASSETS';
export const ADD_PORTFOLIO_ASSET = 'ADD_PORTFOLIO_ASSET';
export const UPDATE_PORTFOLIO_ASSET = 'UPDATE_PORTFOLIO_ASSET';
export const REMOVE_PORTFOLIO_ASSET = 'REMOVE_PORTFOLIO_ASSET';

// watchlist
export const LOAD_WATCHLIST = 'LOAD_WATCHLIST';
export const LOAD_WATCHLIST_ASSETS = 'LOAD_WATCHLIST_ASSETS';
export const ADD_WATCHLIST_ASSET = 'ADD_WATCHLIST_ASSET';
export const UPDATE_WATCHLIST_ASSET = 'UPDATE_WATCHLIST_ASSET';
export const REMOVE_WATCHLIST_ASSET = 'REMOVE_WATCHLIST_ASSET';
